version: "3.8"

services:
  python_server:
    build:
      context: ./ai_grpc_server
      dockerfile: Dockerfile
    image: python_server:latest
    ports:
      - 50051:50051
    container_name: python_server
    environment:
      PYTHONPATH: .
    command: python3 src/main.py

  nest_server:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    image: nest_server:latest
    ports:
      - 3000:3000
    container_name: nest_server
    depends_on:
      - python_server
    command: npm run start
