version: "3.8"

services:
  python_server:
    image: ${DOCKERHUB_USERNAME}/python_grpc_server:latest
    expose:
      - "50051"
    container_name: python_server
    environment:
      PYTHONPATH: .
    command: python3 src/main.py

  nest_server:
    image: ${DOCKERHUB_USERNAME}/nest_gateway:latest
    expose:
      - "3000"
    container_name: nest_server
    depends_on:
      - python_server
      - nginx_server
    command: npm run start

  nginx_server:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx_server:latest
    ports:
      - 80:80
    container_name: nginx_server
    command: nginx -g 'daemon off;'
