version: "3.8"

services:
  python_server:
    image: ${ DOCKERHUB_USERNAME }/python_grpc_server:latest
    ports:
      - ${ PYTHON_GRPC_PORT }:${ PYTHON_GRPC_PORT }
    container_name: python_server
    environment:
      PYTHONPATH: .
    command: python3 src/main.py

  nest_server:
    image: ${ DOCKERHUB_USERNAME }/nest_gateway:latest
    ports:
      - ${ NEST_GATEWAY_PORT }:${ NEST_GATEWAY_PORT }
    container_name: nest_server
    depends_on:
      - python_server
    command: npm run start
