# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.proto import model_pb2 as src_dot_proto_dot_model__pb2


class ModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getLabel = channel.unary_unary(
                '/model.ModelService/getLabel',
                request_serializer=src_dot_proto_dot_model__pb2.ModelParam.SerializeToString,
                response_deserializer=src_dot_proto_dot_model__pb2.ModelReturn.FromString,
                )


class ModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getLabel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getLabel': grpc.unary_unary_rpc_method_handler(
                    servicer.getLabel,
                    request_deserializer=src_dot_proto_dot_model__pb2.ModelParam.FromString,
                    response_serializer=src_dot_proto_dot_model__pb2.ModelReturn.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getLabel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.ModelService/getLabel',
            src_dot_proto_dot_model__pb2.ModelParam.SerializeToString,
            src_dot_proto_dot_model__pb2.ModelReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
