name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Environment Variables File for Production
        run: |
          echo "$ENV_FILE" >> ./api_gateway/.env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}

      - name: Proxy Build And Push1
        uses: docker/build-push-action@v3
        with:
          context: ./ai_grpc_server
          file: ./ai_grpc_server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python_grpc_server

      - name: Proxy Build And Push2
        uses: docker/build-push-action@v3
        with:
          context: ./api_gateway
          file: ./api_gateway/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nest_gateway

  deploy:
    needs: build
    runs-on: [self-hosted, label-go]
    steps:
      - name: Generate Environment Variables
        run: |
          export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}

          export PYTHON_GRPC_PORT=${{ secrets.PYTHON_GRPC_PORT }}

          export NEST_GATEWAY_PORT=${{ secrets.NEST_GATEWAY_PORT }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PYTHON_GRPC_PORT: ${{ secrets.PYTHON_GRPC_PORT }}
          NEST_GATEWAY_PORT: ${{ secrets.NEST_GATEWAY_PORT }}

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Remove Origin Container
        run: |
          docker rm -f $(docker ps -aq)

          docker rmi -f $(docker images -q)

      - name: Docker run
        if: failure()
        run: |
          docker-compose up
